// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'package:args/command_runner.dart';
import 'package:gg_console_colors/gg_console_colors.dart' show cH2;
import 'package:gg_log/gg_log.dart';

import '../engine/run_dna_test.dart';
import '../util/dna_config.dart';
import '../util/dna_fs.dart';
import '../util/dna_fs_io.dart';
import '../util/dna_layout.dart';
import '../util/layer_graph.dart';
import '../util/package_managers.dart';
import '../util/package_resolution.dart';
import '../util/process_run.dart';
import '../util/process_run_io.dart';

/// Content of the placed Dart wrapper test.
const String dartWrapperTest = '''
// Placed by `helix init` — instantiates and verifies this project's DNA
// on every test run. The logic lives in the helix dev-dependency and is
// updated through normal dependency updates.

import 'package:helix/helix.dart';
import 'package:test/test.dart';

void main() {
  test(
    'dna is instantiated and unmodified',
    () => runDnaTest(),
    timeout: const Timeout(Duration(minutes: 2)),
  );
}
''';

/// Content of the placed vitest wrapper spec.
const String tsWrapperTest = '''
// Placed by `helix init` — instantiates and verifies this project's DNA
// on every test run. The logic lives in the @tssuite/helix-js
// dev-dependency and is updated through normal dependency updates.

import { runDnaTest } from '@tssuite/helix-js';
import { test } from 'vitest';

test(
  'dna is instantiated and unmodified',
  async () => {
    await runDnaTest();
  },
  120000,
);
''';

/// Path of the getting-started doc below the project root.
///
/// It is DNA content, not a loose file: helix ships the same path in its
/// own base DNA, which is layer 0 of every project. The engine therefore
/// adopts the copy placed here — a hand-written file below `dna/` of a
/// `role: project` repo would be deleted on the first run — and
/// instantiates it to `doc/hello_world.md`.
const String helloWorldDnaPath = '$dnaDirname/doc/hello_world.md';

/// Content of [helloWorldDnaPath]. Helix's own `dna/doc/hello_world.md`
/// ships exactly this text; `test/commands/init_test.dart` compares the
/// two so the placed copy is adopted instead of rewritten.
const String helloWorldDoc = '''
# Hello DNA

`helix init` placed this file at `dna/doc/hello_world.md`, and the DNA
engine instantiates it to `doc/hello_world.md`. Those two copies are the
whole idea in miniature: `dna/` holds the merged DNA, the project holds
the instances made from it.

## 1. The config: `dna/_dna.json`

The only place DNA configuration lives. `role: "project"` says that `dna/`
is generated by helix, and `layers` lists the DNA packages to apply — in
application order, last layer wins.

## 2. Add the DNA packages you want

DNA packages are ordinary packages. `helix add` installs one as a
dev-dependency and appends its name to `layers`:

```bash
helix add dna_dart                                  # pub package
helix add @tssuite/dna-base                         # npm package
helix add https://github.com/ggsuite/dna_base.git   # git repository
```

Declaring the dependency by hand works as well — then list it under
`layers` yourself, because a dependency that is not listed is not a
layer.

## 3. Run your tests — that is the engine

`helix init` placed `test/dna/dna_test.dart` (Dart) or
`test/dna/dna.spec.ts` (TypeScript). Every test run instantiates the DNA
and verifies that the instances still match it:

```bash
dart test        # or: pnpm test
helix build      # the same run, without a test framework
```

The first run writes `dna/`, the instances and `dna/_generated.json`, and
commits exactly those files as `#gg: generated DNA`.

## 4. What lands where

| In the DNA                     | Instantiated to         |
| ------------------------------ | ----------------------- |
| `dna/LICENSE`                  | `LICENSE`               |
| `dna/doc/hello_world.md`       | `doc/hello_world.md`    |
| `dna/dot-vscode/settings.json` | `.vscode/settings.json` |
| `dna/_vars.json`               | — private, stays inside |

A leading dot is escaped as `dot-`, because publishing to pub drops every
path that starts with a dot. Any path segment starting with `_` is
private and never becomes an instance.

## 5. Do not edit generated files

An instance you change locally is copied to a folder below the system
temp directory and then overwritten with the DNA content; the report
prints that backup path. Change what a layer ships instead:

- a same-path file in a later layer replaces the file,
- `X.overrides.json` merges field-wise into `X.json`,
- `X.overrides.md` replaces the sections a markdown file marks.

Every existing file a run would overwrite or delete has to be committed
first, so each overwrite stays recoverable through git.

## Next steps

- Add your layers to `dna/_dna.json`.
- The helix README is the full reference: variables, overrides, the
  managed `CLAUDE.md` block and the resolution rules.
''';

/// Skeleton written to `dna/_dna.json` when it does not exist yet, with
/// [layers] pre-filled from the DNA packages the project has installed.
String dnaConfigSkeleton(List<String> layers) {
  final list = layers.map((l) => '"$l"').join(', ');
  return '''
{
  // DNA configuration — the only place DNA config lives.
  // The engine only ever reads this file; dna/_generated.json is its
  // output. Comments and trailing commas are tolerated.
  "version": $dnaFormatVersion,

  // The DNA layers, in application order — later layers win. Package
  // names as declared in pubspec.yaml / package.json, never paths.
  // Transitive parents come from each layer's own dna/_dna.json.
  "layers": [$list]

  // "vars": { "dnaProjectName": "my-project" },
  // "claude": { "claudeMdInclude": ["doc/conventions"] }
}
''';
}

// .............................................................................
/// Prepares a project for the DNA engine: makes sure there is a manifest,
/// adds helix as a dev dependency, and places the configuration, the
/// getting-started doc and the wrapper test. The instantiation itself runs
/// inside that test on every test run.
class Init extends Command<dynamic> {
  /// Constructor. [host] and [processRun] are the injectable seams to the
  /// file system and to the package managers.
  Init({required this.ggLog, DnaHost? host, ProcessRun? processRun})
    : _host = host ?? IoDnaHost(),
      _processRun = processRun ?? ioProcessRun {
    argParser.addOption(
      'target',
      abbr: 't',
      help: 'The project folder to initialize.',
      defaultsTo: '.',
    );
  }

  /// The log function.
  final GgLog ggLog;

  final DnaHost _host;

  final ProcessRun _processRun;

  @override
  final name = 'init';

  @override
  final description = 'Places the DNA test that instantiates the project DNA';

  // ...........................................................................
  @override
  Future<void> run() async {
    final target = (argResults!['target'] as String).replaceAll(r'\', '/');
    final root = target == '.' ? '.' : target;

    final isDart = _host.existsFile('$root/pubspec.yaml');
    var isNode = _host.existsFile('$root/package.json');
    if (!isDart && !isNode) {
      _npmInit(root);
      isNode = true;
    }

    if (isNode) _addNodeDevDependency(root);
    if (isDart) _addPubDevDependency(root);

    final layers = suggestDnaLayers(
      _host,
      root,
      PackageResolution.read(_host, root),
    );
    _place('$root/$dnaConfigPath', dnaConfigSkeleton(layers));
    _place('$root/$helloWorldDnaPath', helloWorldDoc);

    // Without a test framework no wrapper is placed — that is a project
    // shape, not a problem: `helix build` runs the same instantiation.
    if (isDart && declaresPubDependency(_host, root, dartTestPackage)) {
      _place('$root/test/dna/dna_test.dart', dartWrapperTest);
    }
    if (isNode && declaresNodeDependency(_host, root, nodeTestPackage)) {
      _place('$root/test/dna/dna.spec.ts', tsWrapperTest);
    }

    if (layers.isNotEmpty) {
      ggLog(cDetail('✓ Layers: ${layers.join(', ')}'));
    }
    ggLog('');
    ggLog(cH2('✓ Initialized.'));
    ggLog('');
    // Concatenated, never nested: a cCmd inside a cAction resets the
    // yellow and the rest of the sentence loses it.
    ggLog(
      '${cAction('Add dna by running ')}'
      '${cCmd('gg dna add <dnaPackage>')}${cAction('.')}',
    );
    ggLog('');
  }

  // ...........................................................................
  /// Bootstraps a `package.json` with npm's defaults — the way on from a
  /// folder that is neither a Dart nor a node project.
  void _npmInit(String root) {
    final result = _processRun(
      NodePackageManager.npm.executable,
      npmInitArgs,
      workingDirectory: root,
    );
    if (!result.isSuccess || !_host.existsFile('$root/package.json')) {
      usageException(
        'No pubspec.yaml and no package.json in "$root", and '
        '${NodePackageManager.npm.executable} '
        '${npmInitArgs.join(' ')} did not create one:\n'
        '${result.failureOutput}',
      );
    }
    ggLog(cDetail('✓ Created package.json'));
  }

  // ...........................................................................
  /// Adds the DNA engine to the node dev dependencies, with the package
  /// manager this project uses.
  void _addNodeDevDependency(String root) {
    if (declaresNodeDependency(_host, root, helixNodePackage)) {
      ggLog(cDetail('✓ Kept existing dev dependency $helixNodePackage'));
      return;
    }
    final manager = detectNodePackageManager(_host, root);
    _addDevDependency(
      root,
      manager.executable,
      manager.addDevArgs(helixNodePackage),
    );
  }

  // ...........................................................................
  /// Adds the DNA engine to the pub dev dependencies.
  void _addPubDevDependency(String root) {
    if (declaresPubDependency(_host, root, helixPubPackage)) {
      ggLog(cDetail('✓ Kept existing dev dependency $helixPubPackage'));
      return;
    }
    _addDevDependency(
      root,
      pubExecutable(_host, root),
      pubAddDevArgs(helixPubPackage),
    );
  }

  // ...........................................................................
  /// Runs one dependency-adding command. A failure is reported with the
  /// command to repeat by hand instead of aborting: the configuration and
  /// the doc are worth placing either way.
  void _addDevDependency(String root, String executable, List<String> args) {
    final command = '$executable ${args.join(' ')}';
    final result = _processRun(executable, args, workingDirectory: root);
    if (result.isSuccess) {
      ggLog(cDetail('✓ $command'));
      return;
    }
    ggLog('! $command failed — run it manually:\n${result.failureOutput}');
  }

  // ...........................................................................
  void _place(String path, String content) {
    if (_host.existsFile(path)) {
      ggLog(cDetail('✓ Kept existing $path'));
      return;
    }
    _host.writeString(path, content);
    ggLog(cDetail('✓ Placed $path'));
  }
}
