// @license
// Copyright (c) 2019 - 2026 Dr. Gabriel Gatzsche. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:convert';

import 'package:yaml/yaml.dart';

import 'dna_fs.dart';
import 'dna_layout.dart';
import 'dna_vars.dart';
import 'jsonc.dart';

/// Path of the DNA config file relative to the project root — the only
/// place DNA configuration lives since gg_dna 5.0.
const String dnaConfigPath = '.gg/dna.json';

/// The role a repository plays in the DNA system.
enum DnaRole {
  /// Authors its `dna/` folder by hand; `dna/` is the last layer of its
  /// own instantiation and is never overwritten.
  dna,

  /// Consumes DNA; `dna/` is fully generated by the engine.
  project,
}

// .............................................................................
/// The Claude tool configuration (`config: claude:`).
class DnaClaudeConfig {
  /// Creates the config.
  const DnaClaudeConfig({this.claudeMdInclude});

  /// Files/folders whose `@`-imports form the managed CLAUDE.md block;
  /// `null` = section absent.
  final List<String>? claudeMdInclude;
}

// .............................................................................
/// The parsed `.gg/dna.json` of a repository.
class DnaConfig {
  /// Creates the config.
  const DnaConfig({
    this.role = DnaRole.project,
    this.order,
    this.pathOverrides = const {},
    this.vars = const {},
    this.fileNaming,
    this.claude = const DnaClaudeConfig(),
  });

  /// The repository's role; defaults to [DnaRole.project].
  final DnaRole role;

  /// Explicit layer order (canonical kebab names); `null` = default order
  /// derived from the dev-dependency declaration order.
  final List<String>? order;

  /// Local path overrides per layer name (development workspaces).
  final Map<String, String> pathOverrides;

  /// Raw variable entries (`null` values delete inherited variables).
  final Map<String, Object?> vars;

  /// Instance file-naming standard; `null` = default by project type.
  final FileNaming? fileNaming;

  /// The Claude tool configuration.
  final DnaClaudeConfig claude;
}

// .............................................................................
/// Reads the DNA config of [targetRoot] from `.gg/dna.json`. A missing
/// file yields the default config. Legacy `dna:` blocks in `pubspec.yaml`,
/// `package.json` or a `dna.yaml` file throw a migration [FormatException].
({DnaConfig config, List<String> warnings}) readDnaConfig(
  DnaHost host,
  String targetRoot,
) {
  _rejectLegacyConfigSources(host, targetRoot);

  final warnings = <String>[];
  final path = '$targetRoot/$dnaConfigPath';
  if (!host.existsFile(path)) {
    return (config: const DnaConfig(), warnings: warnings);
  }

  final decoded = parseJsonc(host.readString(path), sourceLabel: path);
  if (decoded is! Map<String, dynamic>) {
    throw const FormatException(
      '$dnaConfigPath must contain a JSON object.',
    );
  }

  const knownKeys = {
    'role',
    'order',
    'dependencies',
    'vars',
    'fileNaming',
    'config',
  };
  for (final key in decoded.keys) {
    if (!knownKeys.contains(key)) {
      warnings.add('$dnaConfigPath: unknown key "$key" — ignored.');
    }
  }

  return (
    config: DnaConfig(
      role: _parseRole(decoded['role']),
      order: _parseOrder(decoded['order']),
      pathOverrides: _parseDependencies(decoded['dependencies']),
      vars: _parseVars(decoded['vars'], warnings),
      fileNaming: _parseFileNamingValue(decoded['fileNaming']),
      claude: _parseConfigSection(decoded['config'], warnings),
    ),
    warnings: warnings,
  );
}

// .............................................................................
void _rejectLegacyConfigSources(DnaHost host, String targetRoot) {
  if (host.existsFile('$targetRoot/dna.yaml')) {
    throw const FormatException(
      'dna.yaml is no longer read since gg_dna 5.0 — move the DNA config '
      'to .gg/dna.json.',
    );
  }
  final pubspecPath = '$targetRoot/pubspec.yaml';
  if (host.existsFile(pubspecPath)) {
    try {
      final doc = loadYaml(host.readString(pubspecPath));
      if (doc is Map && doc.containsKey('dna')) {
        throw const FormatException(
          'pubspec.yaml must not contain a dna: block since gg_dna 5.0 — '
          'move it to .gg/dna.json.',
        );
      }
    } on YamlException {
      // Not our file to validate.
    }
  }
  final packageJsonPath = '$targetRoot/package.json';
  if (host.existsFile(packageJsonPath)) {
    try {
      final doc = jsonDecode(host.readString(packageJsonPath));
      if (doc is Map && doc['dna'] is Map) {
        throw const FormatException(
          'package.json must not contain a "dna" object since gg_dna 5.0 '
          '— move it to .gg/dna.json.',
        );
      }
    } on FormatException catch (e) {
      if (e.message.contains('since gg_dna 5.0')) rethrow;
      // Not our file to validate.
    }
  }
}

// .............................................................................
DnaRole _parseRole(Object? value) {
  switch (value) {
    case null:
    case 'project':
      return DnaRole.project;
    case 'dna':
      return DnaRole.dna;
    default:
      throw FormatException(
        '$dnaConfigPath: role must be "dna" or "project" — got "$value".',
      );
  }
}

// .............................................................................
List<String>? _parseOrder(Object? value) {
  if (value == null) return null;
  if (value is! List) {
    throw const FormatException('$dnaConfigPath: order must be a list.');
  }
  final order = <String>[];
  for (final entry in value) {
    if (entry is! String || entry.trim().isEmpty) {
      throw const FormatException(
        '$dnaConfigPath: order entries must be non-empty strings.',
      );
    }
    if (order.contains(entry)) {
      throw FormatException(
        '$dnaConfigPath: duplicate order entry "$entry".',
      );
    }
    order.add(entry);
  }
  return order;
}

// .............................................................................
Map<String, String> _parseDependencies(Object? value) {
  if (value == null) return const {};
  if (value is! Map) {
    throw const FormatException(
      '$dnaConfigPath: dependencies must be a map.',
    );
  }
  final overrides = <String, String>{};
  for (final entry in value.entries) {
    final name = entry.key as String;
    final spec = entry.value;
    if (spec is! Map) {
      throw FormatException(
        '$dnaConfigPath: dependency "$name" must be a map.',
      );
    }
    if (spec.containsKey('git')) {
      throw FormatException(
        '$dnaConfigPath: dependency "$name" uses git: — git layers were '
        'removed in gg_dna 5.0. Declare the DNA as dev-dependency in '
        'package.json/pubspec.yaml instead.',
      );
    }
    if (spec.containsKey('version')) {
      throw FormatException(
        '$dnaConfigPath: dependency "$name" declares version: — versions '
        'live in package.json/pubspec.yaml since gg_dna 5.0.',
      );
    }
    final path = spec['path'];
    if (path is! String || path.trim().isEmpty) {
      throw FormatException(
        '$dnaConfigPath: dependency "$name" needs a non-empty path: '
        '(only path overrides are supported here).',
      );
    }
    overrides[name] = path.replaceAll(r'\', '/');
  }
  return overrides;
}

// .............................................................................
Map<String, Object?> _parseVars(Object? value, List<String> warnings) {
  if (value == null) return const {};
  if (value is! Map<String, dynamic>) {
    throw const FormatException('$dnaConfigPath: vars must be an object.');
  }
  final validated = validateDnaVarEntries(
    value,
    sourceLabel: '$dnaConfigPath vars',
  );
  warnings.addAll(validated.warnings);
  return validated.entries;
}

// .............................................................................
FileNaming? _parseFileNamingValue(Object? value) {
  if (value == null) return null;
  if (value is! String) {
    throw const FormatException(
      '$dnaConfigPath: fileNaming must be a string.',
    );
  }
  return parseFileNaming(value);
}

// .............................................................................
DnaClaudeConfig _parseConfigSection(Object? value, List<String> warnings) {
  if (value == null) return const DnaClaudeConfig();
  if (value is! Map) {
    throw const FormatException(
      '$dnaConfigPath: config must be an object.',
    );
  }
  for (final key in value.keys) {
    if (key != 'claude') {
      warnings.add('$dnaConfigPath: unknown config section "$key".');
    }
  }
  final claude = value['claude'];
  if (claude == null) return const DnaClaudeConfig();
  if (claude is! Map) {
    throw const FormatException(
      '$dnaConfigPath: config.claude must be an object.',
    );
  }
  if (claude.containsKey('skills')) {
    throw const FormatException(
      '$dnaConfigPath: config.claude.skills was removed in gg_dna 5.0 — '
      'ship skills as instances at dna/.claude/skills/<name>.',
    );
  }
  for (final key in claude.keys) {
    if (key != 'claude_md') {
      warnings.add('$dnaConfigPath: unknown config.claude key "$key".');
    }
  }
  final claudeMd = claude['claude_md'];
  if (claudeMd == null) return const DnaClaudeConfig();
  if (claudeMd is! Map) {
    throw const FormatException(
      '$dnaConfigPath: config.claude.claude_md must be an object.',
    );
  }
  final include = claudeMd['include'];
  if (include == null) return const DnaClaudeConfig(claudeMdInclude: []);
  if (include is! List) {
    throw const FormatException(
      '$dnaConfigPath: config.claude.claude_md.include must be a list.',
    );
  }
  final paths = <String>[];
  for (final entry in include) {
    if (entry is! String || entry.trim().isEmpty) {
      throw const FormatException(
        '$dnaConfigPath: include entries must be non-empty strings.',
      );
    }
    paths.add(entry.replaceAll(r'\', '/'));
  }
  return DnaClaudeConfig(claudeMdInclude: paths);
}
