// @license
// Copyright (c) 2019 - 2026 Dr. Gabriel Gatzsche. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dna_fs.dart';
import 'dna_layout.dart';
import 'dna_vars.dart';
import 'jsonc.dart';

/// Path of the DNA config file relative to the project root — the only
/// place DNA configuration lives.
///
/// It sits inside `dna/` because that is the one folder both ecosystems
/// publish: `pub` drops every path with a leading dot, so a config below
/// `.gg/` never reaches a pub-installed consumer.
const String dnaConfigPath = '$dnaDirname/$dnaConfigFilename';

/// The role a repository plays in the DNA system.
enum DnaRole {
  /// Authors its `dna/` folder by hand; `dna/` is the last layer of its
  /// own instantiation and is never overwritten. This is also what marks
  /// a package as a DNA layer — a `dna/` folder alone does not.
  dna,

  /// Consumes DNA; `dna/` is fully generated by the engine.
  project,
}

// .............................................................................
/// The Claude tool configuration (`claude:`).
class DnaClaudeConfig {
  /// Creates the config.
  const DnaClaudeConfig({this.claudeMdInclude});

  /// Files/folders whose `@`-imports form the managed CLAUDE.md block;
  /// `null` = section absent.
  final List<String>? claudeMdInclude;
}

// .............................................................................
/// The parsed `dna/_dna.json` of a repository.
class DnaConfig {
  /// Creates the config.
  const DnaConfig({
    this.role = DnaRole.project,
    this.layers = const [],
    this.vars = const {},
    this.claude = const DnaClaudeConfig(),
  });

  /// The repository's role; defaults to [DnaRole.project].
  final DnaRole role;

  /// The DNA layers in application order, named by the package name they
  /// are declared under in `pubspec.yaml` / `package.json`. Never paths —
  /// local checkouts are wired up by gg_localize_refs instead.
  final List<String> layers;

  /// Raw variable entries (`null` values delete inherited variables).
  final Map<String, Object?> vars;

  /// The Claude tool configuration.
  final DnaClaudeConfig claude;
}

// .............................................................................
/// Reads the DNA config of [targetRoot] from `dna/_dna.json`. A missing
/// file yields the default config — but only when there is no `dna/`
/// folder at all. A `dna/` folder without `_dna.json` is an error: the
/// config is the only thing that says whether that folder is
/// hand-authored (`role: dna`) or engine-generated, and defaulting to
/// `project` would let the engine wipe a hand-written DNA. Run
/// `gg_dna init` to place the config.
///
/// [packageLabel] names the layer package when [targetRoot] is a resolved
/// layer rather than the target itself — it turns parse errors into
/// messages that point at the right repository.
({DnaConfig config, List<String> warnings}) readDnaConfig(
  DnaHost host,
  String targetRoot, {
  String? packageLabel,
}) {
  final warnings = <String>[];
  final path = '$targetRoot/$dnaConfigPath';
  final where =
      packageLabel == null ? dnaConfigPath : '$packageLabel: $dnaConfigPath';

  if (!host.existsFile(path)) {
    if (host.existsDir('$targetRoot/$dnaDirname')) {
      throw FormatException(
        '$where is missing, but a $dnaDirname/ folder exists — the config '
        'is what declares whether that folder is hand-authored '
        '("role": "dna") or generated. Run `gg_dna init` to place it.',
      );
    }
    return (config: const DnaConfig(), warnings: warnings);
  }

  final decoded = parseJsonc(host.readString(path), sourceLabel: path);
  if (decoded is! Map<String, dynamic>) {
    throw FormatException('$where must contain a JSON object.');
  }

  _requireFormatVersion(decoded['version'], where);

  const knownKeys = {
    'version',
    'role',
    'layers',
    'vars',
    'claude',
  };
  for (final key in decoded.keys) {
    if (!knownKeys.contains(key)) {
      warnings.add('$where: unknown key "$key" — ignored.');
    }
  }

  return (
    config: DnaConfig(
      role: _parseRole(decoded['role'], where),
      layers: _parseLayers(decoded['layers'], where),
      vars: _parseVars(decoded['vars'], where, warnings),
      claude: _parseClaude(decoded['claude'], where, warnings),
    ),
    warnings: warnings,
  );
}

// .............................................................................
void _requireFormatVersion(Object? value, String where) {
  if (value == dnaFormatVersion) return;
  throw FormatException(
    value == null
        ? '$where: "version" is missing — add "version": $dnaFormatVersion.'
        : '$where: format version $value is not supported — this gg_dna '
            'reads version $dnaFormatVersion.',
  );
}

// .............................................................................
DnaRole _parseRole(Object? value, String where) {
  switch (value) {
    case null:
    case 'project':
      return DnaRole.project;
    case 'dna':
      return DnaRole.dna;
    default:
      throw FormatException(
        '$where: role must be "dna" or "project" — got "$value".',
      );
  }
}

// .............................................................................
List<String> _parseLayers(Object? value, String where) {
  if (value == null) return const [];
  if (value is! List) {
    throw FormatException('$where: layers must be a list.');
  }
  final layers = <String>[];
  for (final entry in value) {
    if (entry is! String || entry.trim().isEmpty) {
      throw FormatException(
        '$where: layers entries must be non-empty package names.',
      );
    }
    if (entry.contains('/') && !entry.startsWith('@')) {
      throw FormatException(
        '$where: layer "$entry" looks like a path — layers are referenced '
        'by the package name they are declared under in pubspec.yaml / '
        'package.json. Use gg_localize_refs for local checkouts.',
      );
    }
    if (layers.contains(entry)) {
      throw FormatException('$where: duplicate layer "$entry".');
    }
    layers.add(entry);
  }
  return layers;
}

// .............................................................................
Map<String, Object?> _parseVars(
  Object? value,
  String where,
  List<String> warnings,
) {
  if (value == null) return const {};
  if (value is! Map<String, dynamic>) {
    throw FormatException('$where: vars must be an object.');
  }
  final validated = validateDnaVarEntries(value, sourceLabel: '$where vars');
  warnings.addAll(validated.warnings);
  return validated.entries;
}

// .............................................................................
DnaClaudeConfig _parseClaude(
  Object? value,
  String where,
  List<String> warnings,
) {
  if (value == null) return const DnaClaudeConfig();
  if (value is! Map) {
    throw FormatException('$where: claude must be an object.');
  }
  for (final key in value.keys) {
    if (key != 'claudeMdInclude') {
      warnings.add('$where: unknown claude key "$key".');
    }
  }
  // Key absent leaves CLAUDE.md alone; `[]` manages an empty block.
  if (!value.containsKey('claudeMdInclude')) return const DnaClaudeConfig();
  final include = value['claudeMdInclude'];
  if (include == null) return const DnaClaudeConfig(claudeMdInclude: []);
  if (include is! List) {
    throw FormatException('$where: claude.claudeMdInclude must be a list.');
  }
  final paths = <String>[];
  for (final entry in include) {
    if (entry is! String || entry.trim().isEmpty) {
      throw FormatException(
        '$where: claude.claudeMdInclude entries must be non-empty strings.',
      );
    }
    paths.add(entry.replaceAll(r'\', '/'));
  }
  return DnaClaudeConfig(claudeMdInclude: paths);
}
