// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import '../util/dna_fs.dart';
import '../util/dna_layout.dart';
import '../util/dna_vars.dart';

/// The base DNA the engine carries itself — layer 0 of every project,
/// below whatever that project declares.
///
/// Kept here as source rather than read from the installed package folder:
/// resolving that folder needs `dart:isolate`, which `dart compile wasm`
/// does not support, so a DNA run inside a WebAssembly build could not
/// find it. Embedded, the engine carries its own base wherever it runs.
///
/// The constants are the source and `dna/` is what consumers get:
/// `test/engine/base_dna_test.dart` repairs the folder from [baseDnaFiles]
/// the way `test/helix_version_test.dart` repairs the version literal.

/// Path of the getting-started doc below the project root.
///
/// It is DNA content, not a loose file: helix ships the same path in its
/// own base DNA, which is layer 0 of every project. The engine therefore
/// adopts the copy placed here — a hand-written file below `dna/` of a
/// `role: project` repo would be deleted on the first run — and
/// instantiates it to `doc/hello_world.md`.
const String helloWorldDnaPath = '$dnaDirname/doc/hello_world.md';

/// Content of [helloWorldDnaPath]. Helix's own `dna/doc/hello_world.md`
/// ships exactly this text; `test/commands/init_test.dart` compares the
/// two so the placed copy is adopted instead of rewritten.
const String helloWorldDoc = '''
# Hello DNA

`helix init` placed this file at `dna/doc/hello_world.md`, and the DNA
engine instantiates it to `doc/hello_world.md`. Those two copies are the
whole idea in miniature: `dna/` holds the merged DNA, the project holds
the instances made from it.

## 1. The config: `dna/_dna.json`

The only place DNA configuration lives. `role: "project"` says that `dna/`
is generated by helix, and `layers` lists the DNA packages to apply — in
application order, last layer wins.

## 2. Add the DNA packages you want

DNA packages are ordinary packages. `helix add` installs one as a
dev-dependency and appends its name to `layers`:

```bash
helix add dna_dart                                  # pub package
helix add @tssuite/dna-base                         # npm package
helix add https://github.com/ggsuite/dna_base.git   # git repository
```

Declaring the dependency by hand works as well — then list it under
`layers` yourself, because a dependency that is not listed is not a
layer.

## 3. Run your tests — that is the engine

`helix init` placed `test/dna/dna_test.dart` (Dart) or
`test/dna/dna.spec.ts` (TypeScript). Every test run instantiates the DNA
and verifies that the instances still match it:

```bash
dart test        # or: pnpm test
helix build      # the same run, without a test framework
```

The first run writes `dna/`, the instances and `dna/_generated.json`, and
commits exactly those files as `#gg: generated DNA`.

## 4. What lands where

| In the DNA                     | Instantiated to         |
| ------------------------------ | ----------------------- |
| `dna/LICENSE`                  | `LICENSE`               |
| `dna/doc/hello_world.md`       | `doc/hello_world.md`    |
| `dna/dot-vscode/settings.json` | `.vscode/settings.json` |
| `dna/_vars.json`               | — private, stays inside |

A leading dot is escaped as `dot-`, because publishing to pub drops every
path that starts with a dot. Any path segment starting with `_` is
private and never becomes an instance.

## 5. Do not edit generated files

An instance you change locally is copied to a folder below the system
temp directory and then overwritten with the DNA content; the report
prints that backup path. Change what a layer ships instead:

- a same-path file in a later layer replaces the file,
- `X.overrides.json` merges field-wise into `X.json`,
- `X.overrides.md` replaces the sections a markdown file marks.

Every existing file a run would overwrite or delete has to be committed
first, so each overwrite stays recoverable through git.

## Next steps

- Add your layers to `dna/_dna.json`.
- The helix README is the full reference: variables, overrides, the
  managed `CLAUDE.md` block and the resolution rules.
''';

// .............................................................................
/// Every file the base DNA ships, keyed by its path below `dna/`.
///
/// `_generated.json` is deliberately absent: it is the engine's own
/// bookkeeping, excluded from a layer's content by `isDnaContent` and
/// never read from a layer.
const Map<String, String> baseDnaFiles = {
  dnaConfigFilename: baseDnaConfig,
  dnaVarsFilename: baseDnaVars,
  baseDnaHelloWorldPath: helloWorldDoc,
};

/// [helloWorldDnaPath] without the leading `dna/` — the key it has in
/// [baseDnaFiles].
const String baseDnaHelloWorldPath = 'doc/hello_world.md';

/// Content of the base DNA's `_dna.json`.
const String baseDnaConfig =
    '''
{
  // The base DNA the engine carries itself: it is applied to every project
  // as layer 0, below whatever that project declares.
  "version": $dnaFormatVersion,

  // No parents — this is the bottom of every tree.
  "layers": []
}
''';

/// Content of the base DNA's `_vars.json` — the base declares none.
const String baseDnaVars = '{}\n';

// .............................................................................
/// Writes [baseDnaFiles] into a fresh temp folder through [host] and
/// returns that folder — the `baseDnaRoot` the engine reads layer 0 from.
///
/// The caller owns the folder and deletes it when the run is over.
String materializeBaseDna(DnaHost host) {
  final root = host.createTempDir('helix_base_dna_');
  baseDnaFiles.forEach((rel, content) {
    host.writeString('$root/$dnaDirname/$rel', content);
  });
  return root;
}
