// @license
// Copyright (c) 2019 - 2026 Dr. Gabriel Gatzsche. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:gg_dna/gg_dna.dart';
import 'package:test/test.dart';

void main() {
  const root = '/t';
  final log = <String>[];

  setUp(log.clear);

  /// A consumer with one DNA layer shipping a LICENSE and a doc.
  MemoryDnaHost makeHost({Map<String, String> extra = const {}}) =>
      MemoryDnaHost(
        files: {
          '$root/package.json': '{"devDependencies": {"a-dna": "^1.0.0"}}',
          '$root/node_modules/a-dna/package.json':
              '{"name": "a-dna", "version": "1.0.0"}',
          '$root/node_modules/a-dna/dna/LICENSE': 'MIT\n',
          '$root/node_modules/a-dna/dna/doc/hello.md': '# Hello\n',
          ...extra,
        },
      );

  Future<void> run(MemoryDnaHost host) => runDnaTest(
        targetRoot: root,
        host: host,
        baseDnaRoot: '/no-base',
        log: log.add,
      );

  group('runDnaTest', () {
    test('first run instantiates and fails once, second run passes', () async {
      final host = makeHost();
      await expectLater(
        () => run(host),
        throwsA(
          isA<Exception>().having(
            (e) => '$e',
            'message',
            contains('review & commit'),
          ),
        ),
      );
      expect(host.existsFile('$root/LICENSE'), isTrue);
      expect(log.any((m) => m.contains('instantiated')), isTrue);

      await run(host);
    });

    test('reports hand-modified files with their DNA source', () async {
      final host = makeHost();
      await expectLater(() => run(host), throwsException);
      host.writeString('$root/doc/hello.md', 'hand edited\n');

      await expectLater(
        () => run(host),
        throwsA(
          isA<Exception>().having(
            (e) => '$e',
            'message',
            allOf(
              contains('generated by the DNA and were modified by hand'),
              contains('  - doc/hello.md'),
              contains('edit instead: a-dna/dna/doc/hello.md'),
            ),
          ),
        ),
      );
    });

    test('reports files with uncommitted work and their DNA source', () async {
      final host = makeHost(extra: {'$root/doc/hello.md': '# My notes\n'});
      host.uncommitted.add('doc/hello.md');

      await expectLater(
        () => run(host),
        throwsA(
          isA<Exception>().having(
            (e) => '$e',
            'message',
            allOf(
              contains('produced by the DNA'),
              contains('edit instead: a-dna/dna/doc/hello.md'),
            ),
          ),
        ),
      );
      expect(host.readString('$root/doc/hello.md'), '# My notes\n');
    });

    test('fails when LICENSE is missing', () async {
      final host = MemoryDnaHost(
        files: {
          '$root/package.json': '{"devDependencies": {"a-dna": "^1.0.0"}}',
          '$root/node_modules/a-dna/package.json':
              '{"name": "a-dna", "version": "1.0.0"}',
          '$root/node_modules/a-dna/dna/doc/hello.md': '# Hello\n',
        },
      );
      await expectLater(() => run(host), throwsException);
      await expectLater(
        () => run(host),
        throwsA(
          isA<Exception>().having(
            (e) => '$e',
            'message',
            contains('LICENSE is missing'),
          ),
        ),
      );
    });

    test('emits warnings and messages through the log', () async {
      final host = makeHost(
        extra: {'$root/.gg/dna.json': '{"unknownKey": 1}'},
      );
      await expectLater(() => run(host), throwsException);
      expect(log.any((m) => m.startsWith('warning: ')), isTrue);
    });

    test('defaults target root and base DNA when not given', () async {
      // The in-memory host keeps this side-effect free: the defaults
      // (current directory, resolved gg_dna package root) are exercised,
      // but nothing is ever read from or written to the real repository.
      final host = MemoryDnaHost();
      await expectLater(
        () => runDnaTest(host: host, log: log.add),
        throwsA(
          isA<Exception>().having(
            (e) => '$e',
            'message',
            contains('review & commit'),
          ),
        ),
      );
      // Only the in-memory host was touched, never the real repository.
      expect(host.files.keys.every((p) => p.contains('/dna/')), isTrue);
    });
  });

  group('runDnaTest on the real file system', () {
    late Directory tmp;

    setUp(() {
      tmp = Directory.systemTemp.createTempSync('gg_dna_run_test_');
    });

    tearDown(() {
      if (tmp.existsSync()) tmp.deleteSync(recursive: true);
    });

    test('instantiates through the default IoDnaHost', () async {
      // No host injected — this covers the real platform binding. The
      // project is an isolated temp folder, never the repository.
      final target = '${tmp.path}/project';
      final emptyBase = '${tmp.path}/base';
      Directory(emptyBase).createSync(recursive: true);
      File('$target/pubspec.yaml')
        ..createSync(recursive: true)
        ..writeAsStringSync('name: consumer\n');

      await expectLater(
        () => runDnaTest(
          targetRoot: target,
          baseDnaRoot: emptyBase,
          log: log.add,
        ),
        throwsA(
          isA<Exception>().having(
            (e) => '$e',
            'message',
            contains('review & commit'),
          ),
        ),
      );
      expect(File('$target/dna/.dna.json').existsSync(), isTrue);
    });
  });

  group('ggDnaPackageRoot', () {
    test('resolves the installed gg_dna package root', () async {
      final path = await ggDnaPackageRoot();
      expect(path, isNot(contains(r'\')));
      expect(path.endsWith('gg_dna'), isTrue, reason: path);
    });
  });

  group('describeDnaSources', () {
    test('names the DNA file to edit instead of the generated one', () {
      expect(
        describeDnaSources(
          ['.vscode/settings.json'],
          {'.vscode/settings.json': 'dna-dart/dna/.vscode/settings.json'},
        ),
        '  - .vscode/settings.json\n'
        '      edit instead: dna-dart/dna/.vscode/settings.json',
      );
    });

    test('marks paths without a DNA source', () {
      expect(
        describeDnaSources(['dna/.dna.json'], const {}),
        '  - dna/.dna.json\n'
        '      no DNA source — generated by gg_dna itself',
      );
    });

    test('renders one block per path', () {
      final report = describeDnaSources(
        ['a.md', 'b.md'],
        {'a.md': 'base-dna/dna/a.md'},
      );
      expect(report.split('\n'), hasLength(4));
      expect(report, contains('  - a.md'));
      expect(report, contains('  - b.md'));
    });
  });

  group('messages', () {
    test('tell the user to edit the DNA source, not the instance', () {
      expect(modifiedInstancesMessage, contains('generated by the DNA'));
      expect(modifiedInstancesMessage, contains('DNA source'));
      expect(uncommittedTargetsMessage, contains('DNA source'));
    });
  });
}
